/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientmanagement;

/**
 *
 * @author DLawrence
 */
import javax.swing.*;
import java.util.*;
import java.text.*;

public class CM_UI extends javax.swing.JFrame {
    /**
     * Creates new form CM_UI
     */
    public CM_UI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblClientRecord = new javax.swing.JLabel();
        btnAddRecord = new javax.swing.JButton();
        lblSchedDetails = new javax.swing.JLabel();
        lblMeetingTracking = new javax.swing.JLabel();
        lblAccountInfo = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblOccupation = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtOccupation = new javax.swing.JTextField();
        lblRating = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        lblGradYear = new javax.swing.JLabel();
        lblStage = new javax.swing.JLabel();
        cmbGradYear = new javax.swing.JComboBox<>();
        cmbType = new javax.swing.JComboBox<>();
        cmbRating = new javax.swing.JComboBox<>();
        cmbStage = new javax.swing.JComboBox<>();
        txtSource = new javax.swing.JTextField();
        lblLastContact = new javax.swing.JLabel();
        lblNextContact = new javax.swing.JLabel();
        cmbLastContact = new javax.swing.JComboBox<>();
        cmbNextContact = new javax.swing.JComboBox<>();
        btn1W = new javax.swing.JButton();
        btn2W = new javax.swing.JButton();
        btn1M = new javax.swing.JButton();
        btn3M = new javax.swing.JButton();
        btn1Y = new javax.swing.JButton();
        btnAddReminder = new javax.swing.JButton();
        btnDateStamp = new javax.swing.JButton();
        btnAddMeeting = new javax.swing.JButton();
        lblType_MT = new javax.swing.JLabel();
        sprClientRecord = new javax.swing.JSeparator();
        sprSchedDetails = new javax.swing.JSeparator();
        sprMeetingTracking = new javax.swing.JSeparator();
        lblQuickContactNotes = new javax.swing.JLabel();
        cmbType_MT1 = new javax.swing.JComboBox<>();
        lblDate_MT = new javax.swing.JLabel();
        cmbType_MT2 = new javax.swing.JComboBox<>();
        cmbDate_MT1 = new javax.swing.JComboBox<>();
        cmbDate_MT2 = new javax.swing.JComboBox<>();
        lblActionItems = new javax.swing.JLabel();
        btnActionItems1 = new javax.swing.JButton();
        btnActionItems2 = new javax.swing.JButton();
        lblDelMeeting = new javax.swing.JLabel();
        btnDelMeeting1 = new javax.swing.JButton();
        btnDelMeeting2 = new javax.swing.JButton();
        sprAccountInfo = new javax.swing.JSeparator();
        btnAddAccount = new javax.swing.JButton();
        lblType_AI = new javax.swing.JLabel();
        cmbType_AI = new javax.swing.JComboBox<>();
        lblOpened = new javax.swing.JLabel();
        cmbOpened = new javax.swing.JComboBox<>();
        lblCompany = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        lblBenefit = new javax.swing.JLabel();
        txtBenefit = new javax.swing.JTextField();
        lblFPO = new javax.swing.JLabel();
        chkFPO = new javax.swing.JCheckBox();
        lblDelMeeting_AI = new javax.swing.JLabel();
        btnDelMeeting_AI = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuickContactNotes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Client Record");
        setMinimumSize(null);
        setResizable(false);

        lblClientRecord.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblClientRecord.setForeground(new java.awt.Color(0, 102, 204));
        lblClientRecord.setText("Client Record");

        btnAddRecord.setText("Add Record");
        btnAddRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRecordActionPerformed(evt);
            }
        });

        lblSchedDetails.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblSchedDetails.setForeground(new java.awt.Color(0, 102, 204));
        lblSchedDetails.setText("Scheduling Details");

        lblMeetingTracking.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblMeetingTracking.setForeground(new java.awt.Color(0, 102, 204));
        lblMeetingTracking.setText("Meeting Tracking");

        lblAccountInfo.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblAccountInfo.setForeground(new java.awt.Color(0, 102, 204));
        lblAccountInfo.setText("Account Information");

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblEmail.setText("Email");

        lblPhone.setText("Phone #");

        lblOccupation.setText("Occupation");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        lblRating.setText("Rating");

        lblType.setText("Type");

        lblSource.setText("Source");

        lblGradYear.setText("Grad Year");

        lblStage.setText("Stage");

        cmbGradYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016" }));

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Resident" }));

        cmbRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AAA" }));

        cmbStage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Education" }));

        lblLastContact.setText("Last Contact");

        lblNextContact.setText("Next Contact");

        cmbLastContact.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01/01/2016" }));

        cmbNextContact.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "02/01/2016" }));

        btn1W.setText("1W");

        btn2W.setText("2W");

        btn1M.setText("1M");

        btn3M.setText("3M");

        btn1Y.setText("1Y");

        btnAddReminder.setText("Add Reminder");

        btnDateStamp.setText("Date Stamp");
        btnDateStamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateStampActionPerformed(evt);
            }
        });

        btnAddMeeting.setText("Add Meeting");

        lblType_MT.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblType_MT.setText("Type");

        lblQuickContactNotes.setText("Quick Contact Notes");

        cmbType_MT1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd", "3rd", "4th" }));

        lblDate_MT.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblDate_MT.setText("Date");

        cmbType_MT2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2nd" }));

        cmbDate_MT1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01/01/2016" }));

        cmbDate_MT2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01/01/2016" }));

        lblActionItems.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblActionItems.setText("Action Items");

        btnActionItems1.setText("AI");
        btnActionItems1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionItems1ActionPerformed(evt);
            }
        });

        btnActionItems2.setText("AI");
        btnActionItems2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionItems2ActionPerformed(evt);
            }
        });

        lblDelMeeting.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblDelMeeting.setText("Delete Meeting");

        btnDelMeeting1.setText("Delete");

        btnDelMeeting2.setText("Delete");

        btnAddAccount.setText("Add Account");

        lblType_AI.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblType_AI.setText("Type");

        cmbType_AI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IDI", "TEST" }));

        lblOpened.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblOpened.setText("Opened");

        cmbOpened.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01/01/2016" }));

        lblCompany.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblCompany.setText("Company");

        lblBenefit.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblBenefit.setText("Benefit");

        lblFPO.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblFPO.setText("FPO/BU");

        lblDelMeeting_AI.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblDelMeeting_AI.setText("Delete Meeting");

        btnDelMeeting_AI.setText("Delete");

        txtQuickContactNotes.setColumns(20);
        txtQuickContactNotes.setRows(5);
        jScrollPane1.setViewportView(txtQuickContactNotes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNextContact, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLastName)
                                            .addComponent(lblPhone)
                                            .addComponent(lblOccupation)
                                            .addComponent(lblEmail))
                                        .addGap(7, 7, 7))
                                    .addComponent(lblLastContact, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cmbLastContact, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDateStamp))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cmbNextContact, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnAddReminder))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btn1W)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn2W)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn1M)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn3M)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn1Y)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSource)
                                .addComponent(lblType, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblRating, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblGradYear, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStage, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSource)
                                .addComponent(cmbRating, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbGradYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbStage, 0, 100, Short.MAX_VALUE))
                            .addComponent(lblQuickContactNotes)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sprAccountInfo)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(sprClientRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSchedDetails)
                                    .addComponent(lblAccountInfo)
                                    .addComponent(btnAddMeeting)
                                    .addComponent(sprSchedDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblType_MT)
                                            .addComponent(cmbType_MT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbType_MT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDate_MT)
                                            .addComponent(cmbDate_MT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbDate_MT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnActionItems2)
                                                    .addComponent(lblActionItems))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lblDelMeeting))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(13, 13, 13)
                                                        .addComponent(btnDelMeeting2))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnActionItems1)
                                                .addGap(39, 39, 39)
                                                .addComponent(btnDelMeeting1))))
                                    .addComponent(btnAddAccount)
                                    .addComponent(lblMeetingTracking)
                                    .addComponent(sprMeetingTracking, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblType_AI)
                                            .addComponent(cmbType_AI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbOpened, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblOpened))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCompany))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblBenefit)
                                            .addComponent(txtBenefit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFPO)
                                            .addComponent(chkFPO))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnDelMeeting_AI)
                                            .addComponent(lblDelMeeting_AI))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblClientRecord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddRecord)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelMeeting_AI)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClientRecord)
                            .addComponent(btnAddRecord))
                        .addGap(2, 2, 2)
                        .addComponent(sprClientRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFirstName)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRating)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblType)
                            .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSource)
                            .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGradYear)
                            .addComponent(cmbGradYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOccupation)
                            .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStage)
                            .addComponent(cmbStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(lblSchedDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sprSchedDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLastContact)
                                .addGap(8, 8, 8)
                                .addComponent(lblNextContact)
                                .addGap(79, 79, 79)
                                .addComponent(lblMeetingTracking))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbLastContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDateStamp)
                                    .addComponent(lblQuickContactNotes))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cmbNextContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAddReminder))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn1W)
                                            .addComponent(btn2W)
                                            .addComponent(btn1M)
                                            .addComponent(btn3M)
                                            .addComponent(btn1Y)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sprMeetingTracking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddMeeting)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblType_MT)
                            .addComponent(lblDate_MT)
                            .addComponent(lblActionItems)
                            .addComponent(lblDelMeeting))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbType_MT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDate_MT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActionItems1)
                            .addComponent(btnDelMeeting1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbType_MT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDate_MT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActionItems2)
                            .addComponent(btnDelMeeting2))
                        .addGap(32, 32, 32)
                        .addComponent(lblAccountInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sprAccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblType_AI)
                            .addComponent(lblOpened)
                            .addComponent(lblCompany)
                            .addComponent(lblBenefit)
                            .addComponent(lblFPO)
                            .addComponent(lblDelMeeting_AI))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(chkFPO))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbType_AI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbOpened, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBenefit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionItems1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionItems1ActionPerformed
        // TODO add your handling code here:
        AIassign_UI actionItemAssign = new AIassign_UI();
        actionItemAssign.setVisible(true);
               
    }//GEN-LAST:event_btnActionItems1ActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void btnActionItems2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionItems2ActionPerformed
        // TODO add your handling code here:
        AIassign_UI actionItemAssign = new AIassign_UI();
        actionItemAssign.setVisible(true);
           
        
    }//GEN-LAST:event_btnActionItems2ActionPerformed

    private void btnAddRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRecordActionPerformed
        int returnValue = 0;
        
        returnValue = JOptionPane.showConfirmDialog(null,
                        "Do you want to add the current information as a NEW client record?",
                        "Add Record",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
        
        if (returnValue == JOptionPane.YES_OPTION){
                //add info to DB here
                addNewRecord();
    		JOptionPane.showMessageDialog(null, "New Client Record Added");
        }
    	else if (returnValue == JOptionPane.NO_OPTION){
                //Do Nothing
    		//JOptionPane.showMessageDialog(null, "No was clicked.");
        }
        
        
    }//GEN-LAST:event_btnAddRecordActionPerformed

    private void btnDateStampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateStampActionPerformed
        String timeStamp = new SimpleDateFormat("MM/dd/yyyy").format(new Date());
        //ADD functionality here for DATE STAMP
    }//GEN-LAST:event_btnDateStampActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CM_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CM_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CM_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CM_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CM_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1M;
    private javax.swing.JButton btn1W;
    private javax.swing.JButton btn1Y;
    private javax.swing.JButton btn2W;
    private javax.swing.JButton btn3M;
    private javax.swing.JButton btnActionItems1;
    private javax.swing.JButton btnActionItems2;
    private javax.swing.JButton btnAddAccount;
    private javax.swing.JButton btnAddMeeting;
    private javax.swing.JButton btnAddRecord;
    private javax.swing.JButton btnAddReminder;
    private javax.swing.JButton btnDateStamp;
    private javax.swing.JButton btnDelMeeting1;
    private javax.swing.JButton btnDelMeeting2;
    private javax.swing.JButton btnDelMeeting_AI;
    private javax.swing.JCheckBox chkFPO;
    private javax.swing.JComboBox<String> cmbDate_MT1;
    private javax.swing.JComboBox<String> cmbDate_MT2;
    private javax.swing.JComboBox<String> cmbGradYear;
    private javax.swing.JComboBox<String> cmbLastContact;
    private javax.swing.JComboBox<String> cmbNextContact;
    private javax.swing.JComboBox<String> cmbOpened;
    private javax.swing.JComboBox<String> cmbRating;
    private javax.swing.JComboBox<String> cmbStage;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JComboBox<String> cmbType_AI;
    private javax.swing.JComboBox<String> cmbType_MT1;
    private javax.swing.JComboBox<String> cmbType_MT2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccountInfo;
    private javax.swing.JLabel lblActionItems;
    private javax.swing.JLabel lblBenefit;
    private javax.swing.JLabel lblClientRecord;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblDate_MT;
    private javax.swing.JLabel lblDelMeeting;
    private javax.swing.JLabel lblDelMeeting_AI;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFPO;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGradYear;
    private javax.swing.JLabel lblLastContact;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMeetingTracking;
    private javax.swing.JLabel lblNextContact;
    private javax.swing.JLabel lblOccupation;
    private javax.swing.JLabel lblOpened;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblQuickContactNotes;
    private javax.swing.JLabel lblRating;
    private javax.swing.JLabel lblSchedDetails;
    private javax.swing.JLabel lblSource;
    private javax.swing.JLabel lblStage;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblType_AI;
    private javax.swing.JLabel lblType_MT;
    private javax.swing.JSeparator sprAccountInfo;
    private javax.swing.JSeparator sprClientRecord;
    private javax.swing.JSeparator sprMeetingTracking;
    private javax.swing.JSeparator sprSchedDetails;
    private javax.swing.JTextField txtBenefit;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextArea txtQuickContactNotes;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
    
    
    
    public void addNewRecord(){
        //pull GUI data
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        String occupation = txtOccupation.getText();
        String rating = cmbRating.getSelectedItem().toString();
        String type = cmbType.getSelectedItem().toString();
        String source = txtSource.getText();
        String gradYear = cmbGradYear.getSelectedItem().toString();
        String stage = cmbStage.getSelectedItem().toString();   
        String lastContact = cmbLastContact.getSelectedItem().toString();
        String nextContact = cmbNextContact.getSelectedItem().toString();
        String quickContactNotes = txtQuickContactNotes.getText();
        String type1_MT = cmbType_MT1.getSelectedItem().toString();
        String type2_MT = cmbType_MT2.getSelectedItem().toString();
        String date1_MT = cmbDate_MT1.getSelectedItem().toString();   
        String date2_MT = cmbDate_MT2.getSelectedItem().toString();
        String type_AI = cmbType_AI.getSelectedItem().toString();
        String opened = cmbOpened.getSelectedItem().toString();
        String company = txtCompany.getText();
        String benefit = txtBenefit.getText();
        boolean FPO_BU = chkFPO.isSelected();
        
        
        //create Record Object and fill with user-submitted info
        ClientRecord createRecord = new ClientRecord(firstName,lastName,email,phone,occupation,rating,
                                                    type,source,gradYear,stage,lastContact,nextContact,
                                                    quickContactNotes,type1_MT,type2_MT,date1_MT,date2_MT,type_AI,opened,
                                                    company,benefit,FPO_BU);
        
        //submit data to database
        createRecord.submitRecord();
        
        //confirm different variable types were set correctly
        String test = createRecord.getFirstName();
        System.out.println(test);
        String test2 = createRecord.getRating();
        System.out.println(test2);
        boolean test3 = createRecord.getFPO();
        System.out.println(test3);    
        
    }

}


